matrix:
  include:
    - language: c
      compiler: gcc
      script: make
    - language: c
      compiler: clang
      script: make
    - language: python
      python: "2.7"
      before_install: pip install cython
      script: python setup.py build_ext
    - language: python
      python: "3.3"
      before_install: pip install cython
      script: python setup.py build_ext
    - language: python
      python: "3.5"
      before_install: pip install cython
      script: python setup.py build_ext
    - language: python
      python: "3.6"
      before_install: pip install cython
      script: python setup.py build_ext
